# Service for running rimu-py Makefile tasks.
#
# Build the rimu-py image using the local UID and GID:
#
# Linux: Local uid and gid should be passed to docker-compose on the
# command-line or in the docker-compose .env file:
#
#     docker-compose build  # UID and GID sourced from .env file.
#     docker-compose build --build-arg UID=`id -u` --build-arg GID=`id -g`
#
# Windows:
#     docker-compose build
#
# Run commands in the rimu-py dev environmant e.g.
#
#     docker-compose run --rm rimu-py
#     docker-compose run --rm rimu-py make resources
#     docker-compose run --rm rimu-py bash
#
version: "3.8"
services:

  rimu-py:
    build:
      context: .
      args: 
        UID: ${UID:-0}
        GID: ${GID:-0}
    image: rimu-py
    volumes:
      - .:/rimu-py
    command: make clean test